SUM-113 - addendum: adding variant
SU-SWS/ace-sulgryphon pull request #100
Opened 2024-05-17 15:48 UTC by mdyoung3

# READY FOR REVIEW/NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2024-05-17 17:14 UTC, mdyoung3 commented
@rebeccahongsf Adding you to make sure about the colors here.

2024-05-17 17:16 UTC, pookmish requested changes

2024-05-17 17:16 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +      '#title' => $this->t('Banner Background Color'),
I think you mean "Card"

2024-05-17 21:35 UTC, rebeccahongsf commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +        'semitransparent_spirited' => $this->t('Semitransparent Spirited Light'),
Colors look good to me, @mdyoung3 😃 Thank you!

2024-05-17 21:41 UTC, rebeccahongsf commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +      '#title' => $this->t('Card Background Color'),
```suggestion
      '#title' => $this->t('Pill Card Background Color'),
```
@mdyoung3 should we call this 'Pill Card Background Color' instead? So content authors know it's for the Pill Card only 😃  Unless we can conditional render this select field to only display when the user selects Pill from the Card Style.

2024-05-18 07:34 UTC, pookmish approved these changes

2024-05-18 07:36 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +    ];
Optionally, you could add `#states` to show the field only when a pill is selected.

2024-05-21 16:43 UTC, merged