SUM-137 - permisison for taxonomy and content type
SU-SWS/ace-sulgryphon pull request #116
Opened 2024-06-11 18:12 UTC by mdyoung3

# READY FOR REVIEW/NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2024-06-12 15:53 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_testimonial.sum_testimonial_headshot.yml
> +uuid: 5ab9c229-f657-4dce-b93d-d116ee593be3
What are these field configs? they don't seem applicable or wanted in the pr.

2024-06-12 15:55 UTC, pookmish commented
You will also need to update the codeception tests. Removing permissions will cause several tests to fail due to access denied. The easiest way is to make classes `abstract` or specific methods as `protected`. Examples are in the supress profile directory.

2024-06-12 17:09 UTC, mdyoung3 commented on docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_testimonial.sum_testimonial_headshot.yml
> +uuid: 5ab9c229-f657-4dce-b93d-d116ee593be3
That's my bad. Not sure where they came from (these fields are already in the ecosystem), but I should have caught them.

2024-06-12 17:14 UTC, mdyoung3 commented on docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_testimonial.sum_testimonial_headshot.yml
> +uuid: 5ab9c229-f657-4dce-b93d-d116ee593be3
@pookmish Gone.

2024-06-12 17:15 UTC, mdyoung3 commented
@pookmish That makes sense. I'll review those.

2024-06-14 21:26 UTC, pookmish commented
Looks like there's at least 1 more test that needs attention.

2024-06-14 22:43 UTC, mdyoung3 commented
@pookmish Seems to be passing now.

2024-06-17 16:07 UTC, pookmish requested changes
Let's remove permissions for the taxonomy vocabularies, menus for those vocabs, and the "books".

2024-06-17 21:56 UTC, mdyoung3 commented
Hm. I think I must have undid that in a rollback while figuring out the tests. Oh, well.

2024-06-17 22:10 UTC, mdyoung3 commented
Never mind. I missed them.

2024-06-18 21:26 UTC, pookmish requested changes
Still need to remove permission for the vocabularies.
![image](https://github.com/SU-SWS/ace-stanfordlagunita/assets/7185045/dca8f3a9-ff89-490c-856f-9016276c73d4)

2024-06-18 21:56 UTC, mdyoung3 commented
@pookmish For all of them? Won't they need to access course-related terms? (I.e., Course Availability, Course Interest Area, etc...)

2024-06-18 21:57 UTC, pookmish commented
Remove access to the vocabularies they dont need for basic pages and the summer courses. Remove access to the vocabularies for "stanford" courses, people, events, publications, etc.

2024-06-18 23:11 UTC, mdyoung3 commented
@pookmish 

I removed access to all but the following taxonomies:

- Basic Page Types (Seems pertinent to metadata)
- Course Availability
- Course Interest Area
- Course Population
- Media Tags
- Shared Tags (Same as basic pages.)

Technically a lot of these data will be imported, but it seems like it should be available to editors in case.

2024-06-19 19:16 UTC, pookmish requested changes
@mdyoung3 I don't know if you lost some changes or what happened. At the time of this comment none of the permissions match the expected. Site managers still have access to all taxonomies, content types, and menus.

## Site managers:
Remove node type permissions for
- Course
- Event
- Event Series
- News
- Person
- Policy
- Publication

Add node type permission for
- Summer courses

Remove Menu access for
- Event Types
- Person Type
- Topics Menu

Remove Access for Book administration
Remove Taxonomy Access for
- Event Audience
- Event Types
- News types
- Person Types
- Publication Types

Add Taxonomy Access for
- Course Availability
- Course Interest Area
- Course Population

# Contributors
Remove Node access for
- Event
- News
- Person
- Publication

Add node access for
- Summer Courses

You might want to start over with your permissions. You can reset your configs using the following:
`git checkout 2.x -- docroot/profiles/lagunita/summer_profile/config/summer/config_split.patch.user.role.* && drush @summer.local cim -y`. Then edit the permissions in the UI and export.

2024-06-19 20:58 UTC, mdyoung3 commented
@pookmish Not sure what happened here. Investigating.

2024-06-19 22:10 UTC, mdyoung3 commented
@pookmish A [commit appears to have been made by me](https://github.com/SU-SWS/ace-stanfordlagunita/pull/116/commits/5602344f311c5ed2321f510b3c3117df2b3987b5) that re-added permissions. I tried to remove the commit from the git history with rebase, but that resulted in quite a few merge conflicts. Might work out better to reset like you suggestion. 

I apologize. I need to be more careful with config importing and exporting between tasks, I suspect.

2024-06-26 14:57 UTC, pookmish requested changes
Still needs permissions removed for Contributors for the following content types
- Course
- Event Series
- Policy

And please review the tests I commented on.

2024-06-26 14:57 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Content/BasicPageCest.php
> +  protected function testH1Tags(AcceptanceTester $I) {
All basic page tests should still work. No permissions were changed with those.

2024-06-26 14:57 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Content/BasicPageCest.php
> +  protected function testMetaData(AcceptanceTester $I) {
All basic page tests should still work. No permissions were changed with those.

2024-06-26 14:57 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/AuthenticatedPermissionsCest.php
> +  protected function testTaxonomyOverviewPage(AcceptanceTester $I) {
This test should still be used. It's unaffected by any permissions.

2024-06-26 14:57 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Contrib/MenuBlockCest.php
> +  protected function testMenuBlockVisibility(AcceptanceTester $I) {
I'm unclear why this test was disabled. I believe it should work since basic pages were not modified in the permissions

2024-06-26 14:57 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/HomePageCest.php
> +abstract class HomePageCest {
This test should be unaffected by the permissions

2024-06-26 14:57 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Paragraphs/MediaWithCaptionCest.php
> +  protected function testMediaParagraph(AcceptanceTester $I) {
This should still work. paragraphs and basic page were not modified.

2024-06-26 14:57 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Paragraphs/StanfordCardCest.php
> +  protected function testCardButtonLinkText(AcceptanceTester $I) {
This should still work. paragraphs and basic page were not modified.

2024-06-26 14:57 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Paragraphs/StanfordCardCest.php
> +  protected function testCardActionLinkText(AcceptanceTester $I) {
This should still work. paragraphs and basic page were not modified.

2024-06-26 14:57 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/SystemSiteConfigCest.php
> +  protected function testSitePages(AcceptanceTester $I) {
This should still work.

2024-06-26 16:12 UTC, mdyoung3 commented on docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Content/BasicPageCest.php
> +  protected function testH1Tags(AcceptanceTester $I) {
@pookmish Did you revoke the anonymous access? Now when I try to access home, it redirects to login. I figured that's why this was failing for me.

2024-06-26 16:13 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Content/BasicPageCest.php
> +  protected function testH1Tags(AcceptanceTester $I) {
I did, but in CI, it's hardwired to allow for the tests. add this if you want to do some tests on your local. 
`$config['user.role.anonymous']['permissions'][99] = 'access content';`

2024-06-26 17:09 UTC, mdyoung3 commented on docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/Content/BasicPageCest.php
> +  protected function testH1Tags(AcceptanceTester $I) {
My local testing seems to be not liking Drupal 10.3. Now more basic page tests failing. Dang. I'll revert these and push them. If they pass, great.

2024-06-26 18:02 UTC, mdyoung3 commented
@pookmish All right. Tests passed. 

> Still needs permissions removed for Contributors for the following content types
> 
> * Course
> * Event Series
> * Policy
> 
> And please review the tests I commented on.

I wondered about the access for those particular nodes for contributors, curiously absent from the list: https://github.com/SU-SWS/ace-stanfordlagunita/pull/116#pullrequestreview-2128926000

The should be restricted now: 

![Screenshot 2024-06-26 at 12 02 07 PM](https://github.com/SU-SWS/ace-stanfordlagunita/assets/8387457/dd5ffe32-2fad-4fd2-850e-e13a6adcaf63)

2024-06-26 20:09 UTC, pookmish approved these changes
Thanks for sticking with it.

2024-06-26 21:17 UTC, pookmish approved these changes

2024-06-26 21:17 UTC, merged