SUM-196 - hiding message type
SU-SWS/ace-sulgryphon pull request #133
Opened 2024-07-17 21:55 UTC by mdyoung3

# READY FOR REVIEW/NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2024-07-17 22:00 UTC, pookmish requested changes
Don't delete the field. Just hide it in the form settings.

2024-07-18 15:14 UTC, pookmish requested changes
I'm good with the config change, but now you'll have to update the acceptance test.

2024-07-19 20:46 UTC, mdyoung3 commented
@pookmish Tests were passing before I rebased with 2.x.

2024-07-19 20:50 UTC, pookmish commented
Just focus on the codeception tests.

2024-07-19 20:51 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/GlobalMessage/GlobalMessageCest.php
> +  protected function testFormSettings(AcceptanceTester $I) {
Are you able to keep the method public and modify it. Because it's still a feature on the site.

2024-07-22 16:19 UTC, mdyoung3 commented on docroot/profiles/lagunita/summer_profile/tests/codeception/acceptance/GlobalMessage/GlobalMessageCest.php
> +  protected function testFormSettings(AcceptanceTester $I) {
I take it these tests run on a non-decoupled site?

2024-07-22 19:17 UTC, pookmish approved these changes
Cool. Thanks!

2024-07-22 19:17 UTC, merged