SUM-254 - Heading Size to cards
SU-SWS/ace-sulgryphon pull request #138
Opened 2024-09-09 16:21 UTC by mdyoung3

# READY FOR REVIEW/NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2024-09-10 19:48 UTC, mdyoung3 commented
@pookmish Did you get a chance to look at this? I believe it's a blocker for Rebecca

2024-09-10 19:51 UTC, pookmish requested changes
There's a merge conflict too. can you review

2024-09-10 19:51 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +      '#empty_option' => $this->t('Default'),
What is "Default" compared to the 3 options?

2024-09-10 19:57 UTC, mdyoung3 commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +      '#empty_option' => $this->t('Default'),
Per the ticket, "uses the Heading Level size."

Maybe @rebeccahongsf can fill in, but it seems like the default applies no alterations.

2024-09-10 19:58 UTC, mdyoung3 commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +      '#empty_option' => $this->t('Default'),
Where as the other options change the font-size.

2024-09-10 20:09 UTC, mdyoung3 commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +      '#empty_option' => $this->t('Default'),
@pookmish Conflict resolved.

2024-09-10 20:19 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +      '#empty_option' => $this->t('Default'),
I'm just looking at it from a content editor perspective. I have no idea if "Default" is larger or smaller than any of the 3 choices.

2024-09-10 20:41 UTC, rebeccahongsf commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +      '#empty_option' => $this->t('Default'),
Cross posting from JIRA @mdyoung3 @pookmish 😎 

That’s a great point and I had the same thoughts as Marc — I assumed that Default would use the default size coming from the Heading Level. The editor would leave the option as-is if they are content with the default typography size from the Heading Level option.

For additional context, I received feedback from Kat and Kerri on adding the Heading Size option was to maintain accessible headings while having them reasonably sized for longer quotes/heading content. 

Feel free to tag me again if there are any additional Qs or concerns!

2024-09-10 20:44 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +      '#empty_option' => $this->t('Default'),
Let's try to keep the conversation in one or the other locations. Please see Jira for my comment.

2024-09-11 15:28 UTC, pookmish approved these changes

2024-09-11 15:28 UTC, merged