Paragraph Collection
SU-SWS/ace-sulgryphon pull request #18
Opened 2023-01-24 01:03 UTC by mdyoung3

# NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2023-02-07 17:41 UTC, pookmish requested changes
Just a couple nit picky things and then I'm good with this. The UI is a little clunky, but we can review that later.

2023-02-07 17:41 UTC, pookmish commented on docroot/sites/default/settings.php
> +}
> Do not include additional settings here

Would it still work to move this into `docroot/sites/default/settings/default.local.settings.php` file?

2023-02-07 17:41 UTC, pookmish commented on .gitignore
> +sulgryphon-nextjs
This is kinda already added at the top `frontend`. Let's just move it up there.

2023-02-07 20:55 UTC, mdyoung3 commented on docroot/sites/default/settings.php
> +}
I'll give it try. 

Removed!

2023-02-07 20:55 UTC, mdyoung3 commented on .gitignore
> +sulgryphon-nextjs
Done!

2023-02-13 18:23 UTC, pookmish approved these changes

2023-02-13 18:33 UTC, merged