Sul23 160 black to card
SU-SWS/ace-sulgryphon pull request #29
Opened 2023-03-10 00:21 UTC by mdyoung3

# READY FOR REVIEW/NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2023-03-10 19:04 UTC, pookmish requested changes
This needs some changes before it will even function correctly

2023-03-10 19:04 UTC, pookmish commented on docroot/profiles/custom/sul_profile/modules/sul_helper/src/Plugin/paragraphs/Behavior/CardBehaviors.php
> +      '#default_value' => $paragraph->getBehaviorSetting('sul_teaser_styles', 'background'),
This must match the ID of this plugin all the time. [see the id](https://github.com/SU-SWS/ace-sulgryphon/pull/29/files#diff-dd83ebd19befcb103b16eec970b6303b9e4443d7d58b88dba133e0cd7b173968R16)
```suggestion
      '#default_value' => $paragraph->getBehaviorSetting('sul_card_styles', 'background'),
```

2023-03-10 19:04 UTC, pookmish commented on docroot/profiles/custom/sul_profile/modules/sul_helper/src/Plugin/paragraphs/Behavior/CardBehaviors.php
> +      '#default_value' => $paragraph->getBehaviorSetting('sul_teaser_styles', 'background_sprinkles'),
```suggestion
      '#default_value' => $paragraph->getBehaviorSetting('sul_card_styles', 'background_sprinkles'),
```

2023-03-10 19:04 UTC, pookmish commented on docroot/profiles/custom/sul_profile/modules/sul_helper/src/Plugin/paragraphs/Behavior/CardBehaviors.php
> +          'select[name="behavior_plugins[sul_teaser_styles][background]"]' => ['value' => ''],
I'm not sure if this is the reason why the state doesn't work. You'll need to review the functionality.
```suggestion
          'select[name="behavior_plugins[sul_card_styles][background]"]' => ['value' => ''],
```

2023-03-10 19:27 UTC, mdyoung3 commented
@pookmish Sorry. I should have caught that. Updating.

2023-03-16 22:57 UTC, mdyoung3 commented
@pookmish I removed the background and update the sprinkles option. 

Ready for review.

2023-03-16 22:58 UTC, pookmish approved these changes
Thanks

2023-03-16 22:58 UTC, merged