Devops 000 ddev config update
SU-SWS/ace-sulgryphon pull request #61
Opened 2024-01-09 21:21 UTC by mdyoung3

# READY FOR REVIEW/NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2024-01-09 21:27 UTC, pookmish requested changes
Just one line I feel is unnecessary.

2024-01-09 21:27 UTC, pookmish commented on .gitignore
> +docroot/sites/**/settings/settings.ddev.php
You should be able to just use `docroot/sites/settings/local.settings.php` or `docroot/sites/[sitename]/settings/local.settings.php` here.

2024-01-09 22:14 UTC, mdyoung3 commented on .gitignore
> +docroot/sites/**/settings/settings.ddev.php
It's an automated file ddev puts there with all the database stuff.

2024-01-09 22:16 UTC, mdyoung3 commented on .gitignore
> +docroot/sites/**/settings/settings.ddev.php
It comes preconfigured with hash salts, system mailer, logging, etc... and other performance tweaks.

2024-01-10 17:19 UTC, pookmish commented on .gitignore
> +docroot/sites/**/settings/settings.ddev.php
ah, i didn't know it does all that stuff. Then you probably also want to edit the `default.local.settings.php` files to include it if it exists.

2024-01-10 17:23 UTC, mdyoung3 commented on .gitignore
> +docroot/sites/**/settings/settings.ddev.php
I've thought of that, but I've been suspicious an update will wipe it clean. I guess I can try it and see.

2024-01-10 17:26 UTC, mdyoung3 commented on .gitignore
> +docroot/sites/**/settings/settings.ddev.php
@pookmish Done. Thanks for the suggestion. Ready again.

2024-01-10 17:30 UTC, pookmish commented on docroot/sites/library/settings/default.local.settings.php
> +if (getenv('IS_DDEV_PROJECT') == 'true' && is_readable($ddev_settings)) {
You can probably just simplify this.
```suggestion
if (file_exists($ddev_settings)) {
```
Also maybe make it an array just in case we wish to add more files. That would make it more identical to other code like [this settings](https://github.com/SU-SWS/ace-sulgryphon/blob/2.x/docroot/sites/settings/global.settings.php#L55)

2024-01-10 17:42 UTC, mdyoung3 commented on docroot/sites/library/settings/default.local.settings.php
> +if (getenv('IS_DDEV_PROJECT') == 'true' && is_readable($ddev_settings)) {
I supposed they engineered it like that so there's no way it could run outside of a ddev environment. I suppose this is a non-issue because no one uses (or at least they shouldn't) use local.settings.php on any environment (except locally).

2024-01-10 17:44 UTC, pookmish commented on docroot/sites/library/settings/default.local.settings.php
> +if (getenv('IS_DDEV_PROJECT') == 'true' && is_readable($ddev_settings)) {
yeah, I appreciate the extra checks, but it's not really needed. Even on local environments, you're probably the only one with the ddev file.

2024-01-10 18:18 UTC, mdyoung3 commented on docroot/sites/library/settings/default.local.settings.php
> +if (getenv('IS_DDEV_PROJECT') == 'true' && is_readable($ddev_settings)) {
@pookmish I just remembered that this snippet is from what Ddev puts in the settings file, which is why. (I forgot since I disabled this feature)

Anyway, I updated the foreach to be more scalable. Ready!

2024-01-10 18:21 UTC, pookmish commented on docroot/sites/library/settings/default.local.settings.php
> +}
Need correct spacing now.
```suggestion
foreach ($additionalSettingsFiles as $additionalSettingsFile) {
  if (file_exists($additionalSettingsFile)) {
    require $additionalSettingsFile;
  }
}
```

2024-01-10 18:25 UTC, mdyoung3 commented on docroot/sites/library/settings/default.local.settings.php
> +}
@pookmish Oops. Okay. it's standardized.

2024-01-10 18:32 UTC, pookmish approved these changes
Thanks for the cycles @mdyoung3

2024-01-10 18:32 UTC, merged