Lando update
SU-SWS/ace-sulgryphon pull request #67
Opened 2024-02-22 19:42 UTC by imonroe

# READY FOR REVIEW/NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2024-02-29 04:34 UTC, pookmish requested changes

2024-02-29 04:34 UTC, pookmish commented on docroot/sites/default/settings/includes.settings.php
> +<?php
This isn't applicable to the `default` directory.

2024-02-29 04:34 UTC, pookmish commented on composer.json
> +        "sync-sul": [
Why not just use a blt command instead? It's already built in: `blt drupal:sync --sitename=library --sync-public-files`

2024-02-29 04:34 UTC, pookmish commented on lando/sul.local.settings.php
> +<?php
Why are any of these settings files necessary? `blt settings` already creates these using the values from `blt/local.blt.yml`. If you set up that file first, then it handles db credentials for you for every site. Add the following to `local.blt.yml`:
```
drupal:
  db:
    database: dbname
    username: drupal
    password: drupal
    host: dbhost
    port: dbport
```
Then just update the lando database to match the pattern: `[dbname]_[sitename]`

2024-02-29 04:34 UTC, pookmish commented on patches/contrib/ui_patterns_views-preview.patch
>  +{%- endif %}
Not sure why there's changes to this file here. it doesn't even look like anything changed.

2024-03-11 23:02 UTC, imonroe commented on lando/sul.local.settings.php
> +<?php
fixed.

2024-03-11 23:02 UTC, imonroe commented on patches/contrib/ui_patterns_views-preview.patch
>  +{%- endif %}
fixed.

2024-03-11 23:04 UTC, imonroe commented on composer.json
> +        "sync-sul": [
The syntax is slightly different (`--site=`, not `--sitename=`), and it didn't work for `supress` until there was an actual `supress` database on prod.  Should be good now.  Actually saves a different step as well.

2024-03-11 23:04 UTC, imonroe commented on docroot/sites/default/settings/includes.settings.php
> +<?php
removed.

2024-03-12 15:53 UTC, pookmish commented on composer.json
> +        "sync-sul": [
I still don't see why these composer commands are desired. the same thing is done with blt.

2024-03-12 15:55 UTC, pookmish requested changes

2024-03-12 15:55 UTC, pookmish commented on lando/example.local.blt.yml
> +multisites:
These get inherited by the `blt.yml` file so adding them here prevents new multisites from being available.

2024-03-12 16:05 UTC, imonroe commented on composer.json
> +        "sync-sul": [
It was for convenience, since the syntax is easier, but no big deal, I removed it.

2024-03-12 16:06 UTC, imonroe commented on lando/example.local.blt.yml
> +multisites:
removed.

2024-03-12 16:26 UTC, pookmish approved these changes
Thanks

2024-03-12 16:26 UTC, merged