SUL-23-447: Added people table view
SU-SWS/ace-sulgryphon pull request #92
Opened 2024-05-01 22:49 UTC by imonroe

# READY FOR REVIEW

# Summary
- I duplicated the existing `People` View, and I changed "Grid" to "Table".

# Review By (Date)
- When does this need to be reviewed by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2024-05-02 15:18 UTC, pookmish requested changes

2024-05-02 15:18 UTC, pookmish commented on docroot/profiles/lagunita/sul_profile/config/sync/views.view.sul_people_table.yml
> +label: 'People Table'
We should name it "Library People" so that we can always add more to it later if we so choose.

2024-05-02 15:18 UTC, pookmish commented on docroot/profiles/lagunita/sul_profile/config/sync/views.view.sul_people_table.yml
> +id: sul_people_table
```suggestion
id: sul_people
```

2024-05-02 15:18 UTC, pookmish commented on docroot/profiles/lagunita/sul_profile/config/sync/views.view.sul_people_table.yml
> +  table_list_all_graphql:
We don't need this. we can re-use the original graphql view.

2024-05-02 15:18 UTC, pookmish commented on docroot/profiles/lagunita/sul_profile/config/sync/views.view.sul_people_table.yml
> +  term_page_table:
Don't need this.

2024-05-02 15:18 UTC, pookmish commented on docroot/profiles/lagunita/sul_profile/config/sync/views.view.sul_people_table.yml
> +uuid: cfd1cb04-412c-451c-b9d7-f0f360654815
You'll also need to update the "List" paragraph to allow this view.

2024-05-06 15:10 UTC, imonroe commented on docroot/profiles/lagunita/sul_profile/config/sync/views.view.sul_people_table.yml
> +label: 'People Table'
It renamed the config file when I changed the label, but I'm not sure that matters.

2024-05-06 15:10 UTC, imonroe commented on docroot/profiles/lagunita/sul_profile/config/sync/views.view.sul_people_table.yml
> +  table_list_all_graphql:
removed the display.

2024-05-06 15:11 UTC, imonroe commented on docroot/profiles/lagunita/sul_profile/config/sync/views.view.sul_people_table.yml
> +  term_page_table:
removed the display

2024-05-06 15:11 UTC, imonroe commented on docroot/profiles/lagunita/sul_profile/config/sync/views.view.sul_people_table.yml
> +uuid: cfd1cb04-412c-451c-b9d7-f0f360654815
Updated list paragraph to allow the view.

2024-05-06 15:14 UTC, pookmish approved these changes

2024-05-06 15:14 UTC, merged