Inital commit
SU-SWS/ace-sulgryphon pull request #94
Opened 2024-05-07 16:11 UTC by mdyoung3

# READY FOR REVIEW/NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2024-05-07 22:23 UTC, pookmish requested changes
A couple quick fixes needed

2024-05-07 22:23 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +    $element['card_variant'] = [
Let's name this something `sum_`

2024-05-07 22:23 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +      '#title' => $this->t('Card variant'),
Add `'#default_option' = $this->t('Default'),`

2024-05-07 22:23 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +      '#options' => [
needs `#default_value`

2024-05-07 23:21 UTC, pookmish requested changes

2024-05-07 23:21 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +      '#options' => [
Still needed

2024-05-08 00:12 UTC, mdyoung3 commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +      '#title' => $this->t('Card variant'),
@pookmish Did you mean #empty_option?

2024-05-08 15:51 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +      '#title' => $this->t('Card variant'),
Sorry, yeah it's `empty_option`

2024-05-08 15:52 UTC, pookmish requested changes

2024-05-08 15:52 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +      '#default_value' => 'oval',
You need to get the value from the paragraph, you can't car code the default value. Besides, the default should be `null` Review the parent class to see how it's done there. you can copy from there.

2024-05-08 18:38 UTC, mdyoung3 commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +      '#default_value' => $paragraph->getBehaviorSetting('sum_card_style', 'sum_card_variant'),
@pookmish Is the plugin_id defined here correctly?

2024-05-08 18:40 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +      '#default_value' => $paragraph->getBehaviorSetting('sum_card_style', 'sum_card_variant'),
no, you use `su_card_styles`

2024-05-08 19:49 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +        'oval' => $this->t('Oval'),
Ok, we got syntax issues out of the way. Now these options, i'm not sure. I only know of the regular rectangle (Default), and the oval. Where do you see the other three options in the designs?

2024-05-08 20:11 UTC, mdyoung3 commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerCardBehaviors.php
> +        'oval' => $this->t('Oval'),
@pookmish Oops. Wrong figam file. I checked with Kat. You're correct.

2024-05-08 20:12 UTC, pookmish approved these changes
Thanks

2024-05-08 20:13 UTC, merged