Adding video paragraph type
SU-SWS/ace-sulgryphon pull request #97
Opened 2024-05-10 17:38 UTC by mdyoung3

# READY FOR REVIEW/NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2024-05-10 18:30 UTC, pookmish requested changes
Small changes needed.

2024-05-10 18:30 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/config/summer/next.next_entity_type_config.config_pages.stanford_basic_site_settings.yml
> +uuid: f61f913e-0efd-42b5-947d-44baac63793d
Can you delete these `next.next_entity_type_config.*` files. I gotta find out why the config ignore isn't working for them.

2024-05-10 18:30 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_video.sum_youtube_url.yml
> +uuid: 93f3b2dc-789f-46c5-9e66-5cea5c691727
Make sure to expose the paragraph type and the field via graphql at `/admin/config/graphql_compose`

2024-05-10 18:30 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_youtube_url.yml
> +field_name: sum_youtube_url
make sure to namespace the fields with the bundle. in this case it should be `sum_video_video` or something. other fields will be like `sum_video_header` or such. See [dev guide documentation](https://sws-devguide.stanford.edu/standards-governance/naming-conventions)

2024-05-13 21:09 UTC, mdyoung3 commented on docroot/profiles/lagunita/summer_profile/config/summer/next.next_entity_type_config.config_pages.stanford_basic_site_settings.yml
> +uuid: f61f913e-0efd-42b5-947d-44baac63793d
Seem to have self-resolved with latest export.

2024-05-14 17:06 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/config/summer/field.field.paragraph.sum_video.sum_youtube_url.yml
> +uuid: 93f3b2dc-789f-46c5-9e66-5cea5c691727
Still incorrectly namespaced

2024-05-14 17:07 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_youtube_url.yml
> +field_name: sum_youtube_url
Still incorrectly namespaced

2024-05-14 17:07 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/config/summer/next.next_entity_type_config.config_pages.stanford_basic_site_settings.yml
> +uuid: f61f913e-0efd-42b5-947d-44baac63793d
They are still in the PR

2024-05-14 17:08 UTC, pookmish requested changes
Still needs the requested feedback addressed

2024-05-14 18:58 UTC, mdyoung3 commented on docroot/profiles/lagunita/summer_profile/config/summer/next.next_entity_type_config.config_pages.stanford_basic_site_settings.yml
> +uuid: f61f913e-0efd-42b5-947d-44baac63793d
Huh. Not sure what happened, but at one point they were gone. 🤷

2024-05-14 19:06 UTC, mdyoung3 commented on docroot/profiles/lagunita/summer_profile/config/summer/field.storage.paragraph.sum_youtube_url.yml
> +field_name: sum_youtube_url
This is really strange. I must have reverted or missed something. I know I fixed this.

Sorry.

2024-05-14 19:27 UTC, mdyoung3 commented
@pookmish Not sure what I did there. But I've double-checked and the changes are now in place for sure.

2024-05-14 19:27 UTC, pookmish approved these changes

2024-05-14 19:28 UTC, merged