SUL23-434: Set up shared tags events view
SU-SWS/ace-sulgryphon pull request #98
Opened 2024-05-13 17:42 UTC by imonroe

# READY FOR REVIEW/NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2024-05-14 17:11 UTC, pookmish requested changes
Needs gql display

2024-05-14 17:11 UTC, pookmish commented on docroot/profiles/lagunita/sul_profile/config/sync/views.view.sul_shared_tag_events.yml
> +  card_grid:
You will want to create a "graphql" display that matches all the filters. Make sure you set the pager setting to match other graphql displays. You can see those in the original event view.

2024-05-20 15:17 UTC, imonroe commented on docroot/profiles/lagunita/sul_profile/config/sync/views.view.sul_shared_tag_events.yml
> +  card_grid:
graphql display added.

2024-05-22 15:02 UTC, pookmish approved these changes
LGTM

2024-05-22 15:02 UTC, merged