SUM-108 - top banner
SU-SWS/ace-sulgryphon pull request #99
Opened 2024-05-14 02:29 UTC by mdyoung3

# READY FOR REVIEW

# Summary
[- Ticket](https://stanfordits.atlassian.net/browse/SUM-108)

# Review By (Date)
- When does this need to be reviewed by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2024-05-16 18:11 UTC, pookmish requested changes
I'll do a review with the configs when I return. But there are things to address for now

2024-05-16 18:11 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/summer_helper.module
> +  $paragraphs_behavior['su_top_banner_styles']['class'] = '\Drupal\summer_helper\Plugin\paragraphs\Behavior\SummerTopBannerBehaviors';
Don't override the plugin. Create a new plugin. It can inherit the same class but we don't want to add options to the existing banner paragraph.

2024-05-16 18:11 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/modules/summer_helper/src/Plugin/paragraphs/Behavior/SummerTopBannerBehaviors.php
> +class SummerTopBannerBehaviors extends ParagraphsBehaviorBase {
Add the plugin definition in the docblock

2024-05-16 18:11 UTC, pookmish commented on docroot/profiles/lagunita/summer_profile/config/summer/paragraphs.paragraphs_type.sum_video.yml
> -uuid: 82402afe-504f-40a8-969c-3b007658f271
Why is this deleted?

2024-05-20 19:07 UTC, mdyoung3 commented on docroot/profiles/lagunita/summer_profile/config/summer/paragraphs.paragraphs_type.sum_video.yml
> -uuid: 82402afe-504f-40a8-969c-3b007658f271
I'm not sure if Git rebase brought it in or config export. It's already in the main branch: https://github.com/SU-SWS/ace-stanfordlagunita/blob/2.x/docroot/profiles/lagunita/summer_profile/config/summer/paragraphs.paragraphs_type.sum_video.yml

2024-05-20 21:19 UTC, mdyoung3 commented on docroot/profiles/lagunita/summer_profile/config/summer/paragraphs.paragraphs_type.sum_video.yml
> -uuid: 82402afe-504f-40a8-969c-3b007658f271
Oh I'm deleting it from the history. Oops. I'll fix this.

2024-05-22 15:57 UTC, pookmish approved these changes
I made some small adjustments to the form settings. This is g2g.

2024-05-22 16:36 UTC, pookmish requested changes
I don't know what happened between this an your `SUM-109-top-banner` PR. You only have a "Top Banner" and no "Arch Banner". I merged 109 as that looked good from my perspective. 

Please review if this PR is still needed or revise for the arch banner.

2024-05-22 17:21 UTC, mdyoung3 commented
@pookmish Good idea. I fixed the merge conflicts on my local. I'll take another look-see (the config imported without any noise or complaint).

2024-05-22 18:55 UTC, mdyoung3 commented
I thought I'd set the Arch PR to merge with this one. Instead it brought in a lot of these changes. Rebasing brought in some SUL stuff. I think I'll copy and paste the Summer changes from this PR into an new one to merge with `2.x`

2024-05-22 19:21 UTC, closed without merging